version: '3.8'
services:
  dev-db:
    container_name: pg_container
    image: postgres:13
    restart: always
    ports:
      - 5434:5432
    environment:
      NODE_ENV: development
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - SheCom

networks:
  SheCom:
